site_name: My Personal Website
site_url: https://MarcelloDe.github.io/mkdocs
use_directory_urls: false
theme:
  name: 'material'
  custom_dir: docs/assets  # Optional: Path to custom CSS/JS
  favicon: 'assets/images/favicon.ico'
  features:
  - content.tabs.link
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Enable search feature
search:
  lang: en
  max_results: 5

# Define the navigation menu structure
nav:
  - Home: index
  - Book Summaries:
      - The First 20 Hours. By Josh Kaufman : Book Summaries/kaufman.md
      - 12 Rules of Life by Jordan Peterson: Book Summaries/peterson.md

  - Subjects:
      - Databases: Subjects/sql.md
  - Projects:
      - How-I-Landed-My-Data-Analyst-Internship: projects/How-I-Landed-My-Data-Analyst-Internship.md
      - IBM Data Science Certification Capstone Project: projects/IBM Data Science Certification Capstone Project.md



# Set the site language (optional)
language: en
